# Data Collection

In [19]:
import os
import pandas as pd

NFL_YEARS = [str(year) for year in range(2010, 2026)]

DATA_FILEPATH = r"Data"

def load_data(NFL_YEAR):
    path = os.path.join(DATA_FILEPATH, f"{NFL_YEAR}.csv")
    NFL = pd.read_csv(path)
    return NFL

for year in NFL_YEARS:
    df = load_data(year)
    print(f"{year} loaded — {len(df)} teams")

display(df.tail())

2010 loaded — 32 teams
2011 loaded — 32 teams
2012 loaded — 32 teams
2013 loaded — 32 teams
2014 loaded — 32 teams
2015 loaded — 32 teams
2016 loaded — 32 teams
2017 loaded — 32 teams
2018 loaded — 32 teams
2019 loaded — 32 teams
2020 loaded — 32 teams
2021 loaded — 32 teams
2022 loaded — 32 teams
2023 loaded — 32 teams
2024 loaded — 32 teams
2025 loaded — 32 teams

,Tm,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
27,New Orleans Saints,6,11,0,0.353,306,383,-77,-4.5,-0.3,-4.9,-5.5,0.6
28,Seattle Seahawks,14,3,0,0.824,483,292,191,11.2,1.6,12.8,6.2,6.7
29,Los Angeles Rams,12,5,0,0.706,518,346,172,10.1,2.4,12.5,8.7,3.9
30,San Francisco 49ers,12,5,0,0.706,437,371,66,3.9,2.1,6.0,3.7,2.3
31,Arizona Cardinals,3,14,0,0.176,355,488,-133,-7.8,3.4,-4.4,-1.0,-3.4

# Logistic Regression Model

In [20]:
import os
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Column indices
TEAM = 0; WINS = 1; LOSSES = 2; TIES = 3; WIN_PERCENTAGE = 4
POINTS_FOR = 5; POINTS_AGAINST = 6; POINTS_DIFFERENTIAL = 7
MARGIN_OF_VICTORY = 8; STRENGTH_OF_SCHEDULE = 9
SIMPLE_RATING_SYSTEM = 10; OFFENSIVE_SRS = 11; DEFENSIVE_SRS = 12

NFL_TEAMS = ['Arizona Cardinals', 'Atlanta Falcons', 'Baltimore Ravens', 'Buffalo Bills',
             'Carolina Panthers', 'Chicago Bears', 'Cincinnati Bengals', 'Cleveland Browns',
             'Dallas Cowboys', 'Denver Broncos', 'Detroit Lions', 'Green Bay Packers',
             'Houston Texans', 'Indianapolis Colts', 'Jacksonville Jaguars', 'Kansas City Chiefs',
             'Las Vegas Raiders', 'Los Angeles Chargers', 'Los Angeles Rams', 'Miami Dolphins',
             'Minnesota Vikings', 'New England Patriots', 'New Orleans Saints', 'New York Giants',
             'New York Jets', 'Philadelphia Eagles', 'Pittsburgh Steelers', 'San Francisco 49ers',
             'Seattle Seahawks', 'Tampa Bay Buccaneers', 'Tennessee Titans', 'Washington Commanders']
NFL_YEARS = [str(year) for year in range(2010, 2026)]

DATA_FILEPATH = "Data"
SCHEDULE_FILEPATH = "Schedule"
MODEL_FILEPATH = "Models/Logistic Regression"
PREDICTIONS_FILEPATH = "Predictions/Logistic Regression"

In [21]:
def read_data(NFL_YEAR, team_name):
    team_data = []
    with open(os.path.join(DATA_FILEPATH, f"{NFL_YEAR}.csv"), "r") as file:
        data = pd.read_csv(file)
        for index, row in data.iterrows():
            if row.iloc[TEAM] == team_name:
                team_data.append([
                    row.iloc[WINS], row.iloc[LOSSES], row.iloc[TIES], row.iloc[WIN_PERCENTAGE],
                    row.iloc[POINTS_FOR], row.iloc[POINTS_AGAINST], row.iloc[POINTS_DIFFERENTIAL],
                    row.iloc[MARGIN_OF_VICTORY], row.iloc[STRENGTH_OF_SCHEDULE],
                    row.iloc[SIMPLE_RATING_SYSTEM], row.iloc[OFFENSIVE_SRS], row.iloc[DEFENSIVE_SRS]
                ])
    return pd.DataFrame(team_data, columns=['W', 'L', 'T', 'W-L%', 'PF', 'PA', 'PD', 'MoV', 'SoS', 'SRS', 'OSRS', 'DSRS'])

In [22]:
def train_model(NFL_YEAR):
    all_data = [read_data(NFL_YEAR, team) for team in NFL_TEAMS]
    combined_data = pd.concat([d for d in all_data if d is not None and len(d) > 0], ignore_index=True)

    for col in combined_data.columns:
        combined_data[col] = pd.to_numeric(combined_data[col], errors='coerce')
    combined_data = combined_data.dropna()

    features = combined_data.drop(columns=['W', 'L', 'T', 'W-L%', 'PF', 'PA', 'MoV'])
    target = combined_data['W-L%']

    X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)
    model = LinearRegression()
    model.fit(X_train, y_train)
    return model

In [23]:
def save_model(NFL_YEAR, model):
    os.makedirs(MODEL_FILEPATH, exist_ok=True)
    with open(os.path.join(MODEL_FILEPATH, f"linear_regression_model_{NFL_YEAR}.pkl"), "wb") as file:
        pickle.dump(model, file)

In [24]:
def make_predictions(NFL_YEAR):
    model_path = os.path.join(MODEL_FILEPATH, f"linear_regression_model_{NFL_YEAR}.pkl")
    with open(model_path, "rb") as file:
        model = pickle.load(file)

    schedule_df = pd.read_csv(os.path.join(SCHEDULE_FILEPATH, f"{NFL_YEAR}.csv"))
    if schedule_df.empty:
        print(f"No schedule found for {NFL_YEAR}")
        return

    team_wins  = {team: 0 for team in NFL_TEAMS}
    team_games = {team: 0 for team in NFL_TEAMS}

    try:
        season_data = pd.read_csv(os.path.join(DATA_FILEPATH, f"{NFL_YEAR}.csv"))
        team_stats = {row.iloc[TEAM]: read_data(NFL_YEAR, row.iloc[TEAM]) for _, row in season_data.iterrows()}
        team_stats = {k: v for k, v in team_stats.items() if v is not None and len(v) > 0}
    except FileNotFoundError:
        print(f"Data file for {NFL_YEAR} not found")
        return

    drop_cols = ['W', 'L', 'T', 'W-L%', 'PF', 'PA', 'MoV']
    for _, row in schedule_df.iterrows():
        winner, loser = row['Winner/tie'], row['Loser/tie']
        if winner not in team_stats or loser not in team_stats:
            continue
        winner_pred = model.predict(team_stats[winner].drop(columns=drop_cols))[0]
        loser_pred  = model.predict(team_stats[loser].drop(columns=drop_cols))[0]
        predicted_winner = winner if winner_pred > loser_pred else loser
        predicted_loser  = loser  if winner_pred > loser_pred else winner
        team_wins[predicted_winner] += 1
        team_games[predicted_winner] += 1
        team_games[predicted_loser]  += 1

    predictions = [
        [team,
         team_stats[team]['W-L%'].iloc[0] if team in team_stats else 0.0,
         team_wins[team] / team_games[team] if team_games[team] > 0 else 0.0]
        for team in NFL_TEAMS
    ]
    predictions_df = pd.DataFrame(predictions, columns=['Team', 'Actual W-L%', 'Predicted W-L%'])
    os.makedirs(PREDICTIONS_FILEPATH, exist_ok=True)
    predictions_df.to_csv(os.path.join(PREDICTIONS_FILEPATH, f"predictions_{NFL_YEAR}.csv"), index=False)
    return predictions_df

In [25]:
for year in NFL_YEARS:
    print(f"Training model for {year}...")
    model = train_model(year)
    save_model(year, model)
    print(f"  Model saved.")
    preds = make_predictions(year)
    print(f"  Predictions made.\n")
    display(preds)  # shows the DataFrame inline in the notebook

Training model for 2010...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.313          0.1250
1         Atlanta Falcons        0.813          0.9375
2        Baltimore Ravens        0.750          0.6875
3           Buffalo Bills        0.250          0.0000
4       Carolina Panthers        0.125          0.0000
5           Chicago Bears        0.688          0.6250
6      Cincinnati Bengals        0.250          0.1250
7        Cleveland Browns        0.313          0.2500
8          Dallas Cowboys        0.375          0.4375
9          Denver Broncos        0.250          0.0000
10          Detroit Lions        0.375          0.3125
11      Green Bay Packers        0.625          0.8750
12         Houston Texans        0.375          0.2500
13     Indianapolis Colts        0.625          0.6250
14   Jacksonville Jaguars        0.500          0.1875
15     Kansas City Chiefs        0.625          0.8750
16      Las Vegas Raiders        0.500          0.6875
17   Los Angeles Chargers        0.563          0.9375
18       Los Angeles Rams        0.438          0.6250
19         Miami Dolphins        0.438          0.3125
20      Minnesota Vikings        0.375          0.1250
21   New England Patriots        0.875          1.0000
22     New Orleans Saints        0.688          0.8125
23        New York Giants        0.625          0.9375
24          New York Jets        0.688          0.6875
25    Philadelphia Eagles        0.625          0.7500
26    Pittsburgh Steelers        0.750          0.9375
27    San Francisco 49ers        0.375          0.3750
28       Seattle Seahawks        0.438          0.2500
29   Tampa Bay Buccaneers        0.625          0.6250
30       Tennessee Titans        0.375          0.5000
31  Washington Commanders        0.375          0.1250

Training model for 2011...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.500          0.3125
1         Atlanta Falcons        0.625          0.6875
2        Baltimore Ravens        0.750          0.8125
3           Buffalo Bills        0.375          0.1250
4       Carolina Panthers        0.375          0.4375
5           Chicago Bears        0.500          0.5000
6      Cincinnati Bengals        0.563          0.6250
7        Cleveland Browns        0.250          0.1250
8          Dallas Cowboys        0.500          0.6875
9          Denver Broncos        0.500          0.2500
10          Detroit Lions        0.625          0.7500
11      Green Bay Packers        0.938          0.9375
12         Houston Texans        0.625          0.8125
13     Indianapolis Colts        0.125          0.0625
14   Jacksonville Jaguars        0.313          0.2500
15     Kansas City Chiefs        0.438          0.0625
16      Las Vegas Raiders        0.500          0.4375
17   Los Angeles Chargers        0.500          0.7500
18       Los Angeles Rams        0.125          0.0000
19         Miami Dolphins        0.375          0.4375
20      Minnesota Vikings        0.188          0.1250
21   New England Patriots        0.813          1.0000
22     New Orleans Saints        0.813          1.0000
23        New York Giants        0.563          0.4375
24          New York Jets        0.500          0.6250
25    Philadelphia Eagles        0.500          0.8125
26    Pittsburgh Steelers        0.750          0.8750
27    San Francisco 49ers        0.813          1.0000
28       Seattle Seahawks        0.438          0.3750
29   Tampa Bay Buccaneers        0.250          0.0000
30       Tennessee Titans        0.563          0.5625
31  Washington Commanders        0.313          0.1250

Training model for 2012...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.313          0.0625
1         Atlanta Falcons        0.813          0.9375
2        Baltimore Ravens        0.625          0.6250
3           Buffalo Bills        0.375          0.3750
4       Carolina Panthers        0.438          0.3750
5           Chicago Bears        0.625          0.9375
6      Cincinnati Bengals        0.625          0.9375
7        Cleveland Browns        0.313          0.3125
8          Dallas Cowboys        0.500          0.1250
9          Denver Broncos        0.813          0.9375
10          Detroit Lions        0.250          0.2500
11      Green Bay Packers        0.688          0.6875
12         Houston Texans        0.750          0.8125
13     Indianapolis Colts        0.688          0.5625
14   Jacksonville Jaguars        0.125          0.0000
15     Kansas City Chiefs        0.125          0.0000
16      Las Vegas Raiders        0.250          0.1875
17   Los Angeles Chargers        0.438          0.6250
18       Los Angeles Rams        0.469          0.3125
19         Miami Dolphins        0.438          0.6250
20      Minnesota Vikings        0.625          0.5625
21   New England Patriots        0.750          1.0000
22     New Orleans Saints        0.438          0.2500
23        New York Giants        0.563          0.7500
24          New York Jets        0.375          0.1875
25    Philadelphia Eagles        0.250          0.0000
26    Pittsburgh Steelers        0.500          0.5625
27    San Francisco 49ers        0.719          0.7500
28       Seattle Seahawks        0.688          0.9375
29   Tampa Bay Buccaneers        0.438          0.5625
30       Tennessee Titans        0.375          0.1250
31  Washington Commanders        0.625          0.6250

Training model for 2013...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.625          0.5000
1         Atlanta Falcons        0.250          0.1875
2        Baltimore Ravens        0.500          0.4375
3           Buffalo Bills        0.375          0.3750
4       Carolina Panthers        0.750          0.8750
5           Chicago Bears        0.500          0.3125
6      Cincinnati Bengals        0.688          1.0000
7        Cleveland Browns        0.250          0.1250
8          Dallas Cowboys        0.500          0.5625
9          Denver Broncos        0.813          1.0000
10          Detroit Lions        0.438          0.8125
11      Green Bay Packers        0.531          0.5625
12         Houston Texans        0.125          0.1250
13     Indianapolis Colts        0.688          0.6875
14   Jacksonville Jaguars        0.250          0.0000
15     Kansas City Chiefs        0.688          0.8750
16      Las Vegas Raiders        0.250          0.1875
17   Los Angeles Chargers        0.563          0.5625
18       Los Angeles Rams        0.438          0.3750
19         Miami Dolphins        0.500          0.5000
20      Minnesota Vikings        0.344          0.1250
21   New England Patriots        0.750          0.7500
22     New Orleans Saints        0.688          0.7500
23        New York Giants        0.438          0.2500
24          New York Jets        0.500          0.1875
25    Philadelphia Eagles        0.625          0.8750
26    Pittsburgh Steelers        0.500          0.7500
27    San Francisco 49ers        0.750          0.8750
28       Seattle Seahawks        0.813          1.0000
29   Tampa Bay Buccaneers        0.250          0.0000
30       Tennessee Titans        0.438          0.3750
31  Washington Commanders        0.188          0.0000

Training model for 2014...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.688          0.5625
1         Atlanta Falcons        0.375          0.1875
2        Baltimore Ravens        0.625          1.0000
3           Buffalo Bills        0.563          0.6875
4       Carolina Panthers        0.469          0.3125
5           Chicago Bears        0.313          0.0625
6      Cincinnati Bengals        0.656          0.5000
7        Cleveland Browns        0.438          0.4375
8          Dallas Cowboys        0.750          0.9375
9          Denver Broncos        0.750          0.8750
10          Detroit Lions        0.688          0.7500
11      Green Bay Packers        0.750          0.8750
12         Houston Texans        0.563          0.6250
13     Indianapolis Colts        0.688          0.6875
14   Jacksonville Jaguars        0.188          0.1250
15     Kansas City Chiefs        0.563          0.7500
16      Las Vegas Raiders        0.188          0.0000
17   Los Angeles Chargers        0.563          0.4375
18       Los Angeles Rams        0.375          0.4375
19         Miami Dolphins        0.500          0.3750
20      Minnesota Vikings        0.438          0.5000
21   New England Patriots        0.750          1.0000
22     New Orleans Saints        0.438          0.4375
23        New York Giants        0.375          0.3125
24          New York Jets        0.250          0.1875
25    Philadelphia Eagles        0.625          0.6250
26    Pittsburgh Steelers        0.688          0.8125
27    San Francisco 49ers        0.500          0.3125
28       Seattle Seahawks        0.750          1.0000
29   Tampa Bay Buccaneers        0.125          0.0000
30       Tennessee Titans        0.125          0.0000
31  Washington Commanders        0.250          0.1875

Training model for 2015...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.813          1.0000
1         Atlanta Falcons        0.500          0.6875
2        Baltimore Ravens        0.313          0.2500
3           Buffalo Bills        0.500          0.5000
4       Carolina Panthers        0.938          1.0000
5           Chicago Bears        0.375          0.1250
6      Cincinnati Bengals        0.750          0.9375
7        Cleveland Browns        0.188          0.0000
8          Dallas Cowboys        0.250          0.0625
9          Denver Broncos        0.750          0.6250
10          Detroit Lions        0.438          0.4375
11      Green Bay Packers        0.625          0.5625
12         Houston Texans        0.563          0.6875
13     Indianapolis Colts        0.500          0.1875
14   Jacksonville Jaguars        0.313          0.4375
15     Kansas City Chiefs        0.688          0.9375
16      Las Vegas Raiders        0.438          0.3750
17   Los Angeles Chargers        0.250          0.0625
18       Los Angeles Rams        0.438          0.4375
19         Miami Dolphins        0.375          0.3750
20      Minnesota Vikings        0.688          0.8125
21   New England Patriots        0.750          1.0000
22     New Orleans Saints        0.438          0.0625
23        New York Giants        0.375          0.5000
24          New York Jets        0.625          0.8750
25    Philadelphia Eagles        0.438          0.3125
26    Pittsburgh Steelers        0.625          0.6250
27    San Francisco 49ers        0.313          0.0625
28       Seattle Seahawks        0.625          0.7500
29   Tampa Bay Buccaneers        0.375          0.4375
30       Tennessee Titans        0.188          0.0625
31  Washington Commanders        0.563          0.8125

Training model for 2016...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.469          0.8750
1         Atlanta Falcons        0.688          1.0000
2        Baltimore Ravens        0.500          0.3750
3           Buffalo Bills        0.438          0.5000
4       Carolina Panthers        0.375          0.1250
5           Chicago Bears        0.188          0.1250
6      Cincinnati Bengals        0.406          0.5625
7        Cleveland Browns        0.063          0.0000
8          Dallas Cowboys        0.813          1.0000
9          Denver Broncos        0.563          0.7500
10          Detroit Lions        0.563          0.2500
11      Green Bay Packers        0.625          0.5625
12         Houston Texans        0.563          0.5625
13     Indianapolis Colts        0.500          0.5000
14   Jacksonville Jaguars        0.188          0.0000
15     Kansas City Chiefs        0.750          0.9375
16      Las Vegas Raiders        0.750          0.6875
17   Los Angeles Chargers        0.313          0.3125
18       Los Angeles Rams        0.250          0.1875
19         Miami Dolphins        0.625          0.3125
20      Minnesota Vikings        0.500          0.8125
21   New England Patriots        0.875          1.0000
22     New Orleans Saints        0.438          0.3125
23        New York Giants        0.688          0.8125
24          New York Jets        0.313          0.1250
25    Philadelphia Eagles        0.438          0.5000
26    Pittsburgh Steelers        0.688          0.8125
27    San Francisco 49ers        0.125          0.0000
28       Seattle Seahawks        0.656          0.7500
29   Tampa Bay Buccaneers        0.563          0.5000
30       Tennessee Titans        0.563          0.4375
31  Washington Commanders        0.531          0.3125

Training model for 2017...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.500          0.3750
1         Atlanta Falcons        0.625          0.7500
2        Baltimore Ravens        0.563          0.7500
3           Buffalo Bills        0.563          0.1875
4       Carolina Panthers        0.688          0.5000
5           Chicago Bears        0.313          0.3125
6      Cincinnati Bengals        0.438          0.3750
7        Cleveland Browns        0.000          0.0000
8          Dallas Cowboys        0.563          0.5625
9          Denver Broncos        0.313          0.2500
10          Detroit Lions        0.563          0.6250
11      Green Bay Packers        0.438          0.1250
12         Houston Texans        0.250          0.1875
13     Indianapolis Colts        0.250          0.0625
14   Jacksonville Jaguars        0.625          0.9375
15     Kansas City Chiefs        0.625          0.6875
16      Las Vegas Raiders        0.375          0.3750
17   Los Angeles Chargers        0.563          0.8125
18       Los Angeles Rams        0.688          0.8750
19         Miami Dolphins        0.375          0.0000
20      Minnesota Vikings        0.813          1.0000
21   New England Patriots        0.813          1.0000
22     New Orleans Saints        0.688          0.8125
23        New York Giants        0.188          0.0000
24          New York Jets        0.313          0.3750
25    Philadelphia Eagles        0.813          1.0000
26    Pittsburgh Steelers        0.813          0.8125
27    San Francisco 49ers        0.375          0.1875
28       Seattle Seahawks        0.563          0.6875
29   Tampa Bay Buccaneers        0.313          0.4375
30       Tennessee Titans        0.563          0.6250
31  Washington Commanders        0.438          0.3125

Training model for 2018...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.188          0.0000
1         Atlanta Falcons        0.438          0.5000
2        Baltimore Ravens        0.625          0.8125
3           Buffalo Bills        0.375          0.1250
4       Carolina Panthers        0.438          0.5625
5           Chicago Bears        0.750          0.9375
6      Cincinnati Bengals        0.375          0.1250
7        Cleveland Browns        0.469          0.3125
8          Dallas Cowboys        0.625          0.7500
9          Denver Broncos        0.375          0.4375
10          Detroit Lions        0.375          0.3125
11      Green Bay Packers        0.406          0.5000
12         Houston Texans        0.688          0.8125
13     Indianapolis Colts        0.625          0.9375
14   Jacksonville Jaguars        0.313          0.2500
15     Kansas City Chiefs        0.750          1.0000
16      Las Vegas Raiders        0.250          0.0625
17   Los Angeles Chargers        0.750          0.8125
18       Los Angeles Rams        0.813          0.9375
19         Miami Dolphins        0.438          0.0625
20      Minnesota Vikings        0.531          0.6250
21   New England Patriots        0.688          0.8750
22     New Orleans Saints        0.813          0.9375
23        New York Giants        0.313          0.3125
24          New York Jets        0.250          0.2500
25    Philadelphia Eagles        0.563          0.5625
26    Pittsburgh Steelers        0.594          0.6250
27    San Francisco 49ers        0.250          0.1875
28       Seattle Seahawks        0.625          0.6875
29   Tampa Bay Buccaneers        0.313          0.1875
30       Tennessee Titans        0.563          0.4375
31  Washington Commanders        0.438          0.0625

Training model for 2019...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.344          0.1875
1         Atlanta Falcons        0.438          0.5000
2        Baltimore Ravens        0.875          1.0000
3           Buffalo Bills        0.625          0.6875
4       Carolina Panthers        0.313          0.0625
5           Chicago Bears        0.500          0.3750
6      Cincinnati Bengals        0.125          0.0625
7        Cleveland Browns        0.375          0.3125
8          Dallas Cowboys        0.500          0.8125
9          Denver Broncos        0.438          0.3125
10          Detroit Lions        0.219          0.2500
11      Green Bay Packers        0.813          0.6875
12         Houston Texans        0.625          0.6250
13     Indianapolis Colts        0.438          0.3750
14   Jacksonville Jaguars        0.375          0.1875
15     Kansas City Chiefs        0.750          0.8750
16      Las Vegas Raiders        0.438          0.0625
17   Los Angeles Chargers        0.313          0.5625
18       Los Angeles Rams        0.563          0.6875
19         Miami Dolphins        0.313          0.0000
20      Minnesota Vikings        0.625          0.9375
21   New England Patriots        0.750          0.9375
22     New Orleans Saints        0.813          0.9375
23        New York Giants        0.250          0.1875
24          New York Jets        0.438          0.4375
25    Philadelphia Eagles        0.563          0.5000
26    Pittsburgh Steelers        0.500          0.5625
27    San Francisco 49ers        0.813          0.9375
28       Seattle Seahawks        0.688          0.5625
29   Tampa Bay Buccaneers        0.438          0.4375
30       Tennessee Titans        0.563          0.8750
31  Washington Commanders        0.188          0.0625

Training model for 2020...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.500          0.6250
1         Atlanta Falcons        0.250          0.3750
2        Baltimore Ravens        0.688          1.0000
3           Buffalo Bills        0.813          1.0000
4       Carolina Panthers        0.313          0.1250
5           Chicago Bears        0.500          0.5625
6      Cincinnati Bengals        0.281          0.0625
7        Cleveland Browns        0.688          0.6250
8          Dallas Cowboys        0.375          0.4375
9          Denver Broncos        0.313          0.0625
10          Detroit Lions        0.313          0.0625
11      Green Bay Packers        0.813          1.0000
12         Houston Texans        0.250          0.3750
13     Indianapolis Colts        0.688          0.8750
14   Jacksonville Jaguars        0.063          0.0000
15     Kansas City Chiefs        0.875          0.8125
16      Las Vegas Raiders        0.500          0.5000
17   Los Angeles Chargers        0.438          0.3750
18       Los Angeles Rams        0.625          0.6875
19         Miami Dolphins        0.625          0.7500
20      Minnesota Vikings        0.438          0.2500
21   New England Patriots        0.438          0.2500
22     New Orleans Saints        0.750          0.9375
23        New York Giants        0.375          0.0625
24          New York Jets        0.125          0.0000
25    Philadelphia Eagles        0.281          0.1875
26    Pittsburgh Steelers        0.750          0.7500
27    San Francisco 49ers        0.375          0.3750
28       Seattle Seahawks        0.750          0.9375
29   Tampa Bay Buccaneers        0.688          0.7500
30       Tennessee Titans        0.688          0.6250
31  Washington Commanders        0.438          0.5625

Training model for 2021...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.647        0.705882
1         Atlanta Falcons        0.412        0.176471
2        Baltimore Ravens        0.471        0.470588
3           Buffalo Bills        0.647        0.882353
4       Carolina Panthers        0.294        0.294118
5           Chicago Bears        0.353        0.176471
6      Cincinnati Bengals        0.588        0.764706
7        Cleveland Browns        0.471        0.235294
8          Dallas Cowboys        0.706        1.000000
9          Denver Broncos        0.412        0.176471
10          Detroit Lions        0.206        0.117647
11      Green Bay Packers        0.765        0.941176
12         Houston Texans        0.235        0.117647
13     Indianapolis Colts        0.529        0.882353
14   Jacksonville Jaguars        0.176        0.000000
15     Kansas City Chiefs        0.706        0.941176
16      Las Vegas Raiders        0.588        0.529412
17   Los Angeles Chargers        0.529        0.764706
18       Los Angeles Rams        0.706        0.823529
19         Miami Dolphins        0.529        0.411765
20      Minnesota Vikings        0.471        0.470588
21   New England Patriots        0.588        0.705882
22     New Orleans Saints        0.529        0.470588
23        New York Giants        0.235        0.000000
24          New York Jets        0.235        0.117647
25    Philadelphia Eagles        0.529        0.647059
26    Pittsburgh Steelers        0.559        0.294118
27    San Francisco 49ers        0.588        0.588235
28       Seattle Seahawks        0.412        0.470588
29   Tampa Bay Buccaneers        0.765        0.941176
30       Tennessee Titans        0.706        0.588235
31  Washington Commanders        0.412        0.294118

Training model for 2022...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.235        0.000000
1         Atlanta Falcons        0.412        0.470588
2        Baltimore Ravens        0.588        0.823529
3           Buffalo Bills        0.813        1.000000
4       Carolina Panthers        0.412        0.294118
5           Chicago Bears        0.176        0.058824
6      Cincinnati Bengals        0.750        0.875000
7        Cleveland Browns        0.412        0.294118
8          Dallas Cowboys        0.706        1.000000
9          Denver Broncos        0.294        0.235294
10          Detroit Lions        0.529        0.823529
11      Green Bay Packers        0.471        0.470588
12         Houston Texans        0.206        0.117647
13     Indianapolis Colts        0.265        0.000000
14   Jacksonville Jaguars        0.529        0.705882
15     Kansas City Chiefs        0.824        0.882353
16      Las Vegas Raiders        0.353        0.411765
17   Los Angeles Chargers        0.588        0.647059
18       Los Angeles Rams        0.294        0.117647
19         Miami Dolphins        0.529        0.647059
20      Minnesota Vikings        0.765        0.588235
21   New England Patriots        0.471        0.588235
22     New Orleans Saints        0.412        0.647059
23        New York Giants        0.559        0.411765
24          New York Jets        0.412        0.235294
25    Philadelphia Eagles        0.824        0.882353
26    Pittsburgh Steelers        0.529        0.411765
27    San Francisco 49ers        0.765        1.000000
28       Seattle Seahawks        0.529        0.764706
29   Tampa Bay Buccaneers        0.471        0.117647
30       Tennessee Titans        0.412        0.294118
31  Washington Commanders        0.500        0.235294

Training model for 2023...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.235        0.117647
1         Atlanta Falcons        0.412        0.352941
2        Baltimore Ravens        0.765        1.000000
3           Buffalo Bills        0.647        0.823529
4       Carolina Panthers        0.118        0.000000
5           Chicago Bears        0.412        0.294118
6      Cincinnati Bengals        0.529        0.529412
7        Cleveland Browns        0.647        0.823529
8          Dallas Cowboys        0.706        1.000000
9          Denver Broncos        0.471        0.176471
10          Detroit Lions        0.706        0.882353
11      Green Bay Packers        0.529        0.705882
12         Houston Texans        0.588        0.647059
13     Indianapolis Colts        0.529        0.470588
14   Jacksonville Jaguars        0.529        0.705882
15     Kansas City Chiefs        0.647        0.764706
16      Las Vegas Raiders        0.471        0.529412
17   Los Angeles Chargers        0.294        0.352941
18       Los Angeles Rams        0.588        0.588235
19         Miami Dolphins        0.647        0.882353
20      Minnesota Vikings        0.412        0.470588
21   New England Patriots        0.235        0.117647
22     New Orleans Saints        0.529        0.941176
23        New York Giants        0.353        0.000000
24          New York Jets        0.412        0.235294
25    Philadelphia Eagles        0.647        0.588235
26    Pittsburgh Steelers        0.588        0.176471
27    San Francisco 49ers        0.706        0.882353
28       Seattle Seahawks        0.529        0.411765
29   Tampa Bay Buccaneers        0.529        0.352941
30       Tennessee Titans        0.353        0.058824
31  Washington Commanders        0.235        0.117647

Training model for 2024...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.471        0.529412
1         Atlanta Falcons        0.471        0.470588
2        Baltimore Ravens        0.706        0.882353
3           Buffalo Bills        0.765        0.941176
4       Carolina Panthers        0.294        0.000000
5           Chicago Bears        0.294        0.235294
6      Cincinnati Bengals        0.529        0.588235
7        Cleveland Browns        0.176        0.000000
8          Dallas Cowboys        0.412        0.235294
9          Denver Broncos        0.588        0.882353
10          Detroit Lions        0.882        1.000000
11      Green Bay Packers        0.647        0.823529
12         Houston Texans        0.588        0.647059
13     Indianapolis Colts        0.471        0.470588
14   Jacksonville Jaguars        0.235        0.176471
15     Kansas City Chiefs        0.882        0.588235
16      Las Vegas Raiders        0.235        0.176471
17   Los Angeles Chargers        0.647        0.764706
18       Los Angeles Rams        0.588        0.705882
19         Miami Dolphins        0.471        0.647059
20      Minnesota Vikings        0.824        0.764706
21   New England Patriots        0.235        0.117647
22     New Orleans Saints        0.294        0.352941
23        New York Giants        0.176        0.117647
24          New York Jets        0.294        0.235294
25    Philadelphia Eagles        0.824        1.000000
26    Pittsburgh Steelers        0.588        0.470588
27    San Francisco 49ers        0.353        0.235294
28       Seattle Seahawks        0.588        0.352941
29   Tampa Bay Buccaneers        0.588        0.823529
30       Tennessee Titans        0.176        0.000000
31  Washington Commanders        0.706        0.764706

Training model for 2025...
  Model saved.
  Predictions made.

                     Team  Actual W-L%  Predicted W-L%
0       Arizona Cardinals        0.176        0.058824
1         Atlanta Falcons        0.471        0.294118
2        Baltimore Ravens        0.471        0.352941
3           Buffalo Bills        0.706        0.823529
4       Carolina Panthers        0.471        0.588235
5           Chicago Bears        0.647        0.764706
6      Cincinnati Bengals        0.353        0.117647
7        Cleveland Browns        0.294        0.294118
8          Dallas Cowboys        0.441        0.294118
9          Denver Broncos        0.824        0.941176
10          Detroit Lions        0.529        0.823529
11      Green Bay Packers        0.559        0.529412
12         Houston Texans        0.706        0.705882
13     Indianapolis Colts        0.471        0.352941
14   Jacksonville Jaguars        0.765        0.882353
15     Kansas City Chiefs        0.353        0.647059
16      Las Vegas Raiders        0.176        0.058824
17   Los Angeles Chargers        0.647        0.529412
18       Los Angeles Rams        0.706        0.882353
19         Miami Dolphins        0.412        0.470588
20      Minnesota Vikings        0.529        0.647059
21   New England Patriots        0.824        1.000000
22     New Orleans Saints        0.353        0.176471
23        New York Giants        0.235        0.352941
24          New York Jets        0.176        0.000000
25    Philadelphia Eagles        0.647        0.823529
26    Pittsburgh Steelers        0.588        0.529412
27    San Francisco 49ers        0.706        0.647059
28       Seattle Seahawks        0.824        1.000000
29   Tampa Bay Buccaneers        0.471        0.352941
30       Tennessee Titans        0.176        0.000000
31  Washington Commanders        0.294        0.058824

# Neural Network Model

# Random Forest Model

# Naive Bayes Model